### ISSUE TITLE
Support for query parameters

### ISSUE THREAD

**Issue by nmalancea** [Lindeneg/cl-fill-link#5]
Thank you for this great little utility.

How hard would it be to add support for **query parameters**?
Next.js Link has it, as seen in the [docs](https://nextjs.org/docs/api-reference/next/link#with-url-object) you referenced in the README.

```
<Link
  href={{
    pathname: '/about',
    query: { name: 'test' },
  }}
>
```

Generates `/about?name=test`.

**Comment by nmalancea** [comment]
I'm still using yours though because of the type safety.

**Comment by Lindeneg** [comment]
Hi there,

I like this idea and since it's supported by Next.js `Link`, I think it's appropriate to add that functionality here. 

I'll have a look at it over the weekend.

**Comment by Lindeneg** [comment]
A new version has now been published. Take a look at the updated portion of the `README` [here](https://github.com/Lindeneg/cl-fill-link#query-params)


Thanks again for the suggestion.

**Comment by nmalancea** [comment]
You're the best. Thanks so much!
